# Generated by Django 6.1 on 2026-08-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ano',
            field=models.IntegerField(default=0),
        ),
    ]
