# Generated by Django 6.1 on 2026-09-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_filme_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
