# Generated by Django 6.1 on 2026-09-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_filme_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(default=''),
        ),
    ]
